site_name: OVOS Messages Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Frameworks:
        - Core: ovos_core.md
        - Audio: ovos_audio.md
        - Listener: dinkum.md
        - Workshop : skills.md
        - GUI: gui.md
        - Persona: persona.md
        - Utils: utils.md
    - Plugins:
        - OPM: opm.md
        - PHAL System: ovos_PHAL_plugin_system.md
        - PHAL ALSA: PHAL_alsa.md
        - PHAL Connectivity: phal_connectivity.md
        - PHAL Network Manager: PHAL_nm.md
        - PHAL IP Geolocation: phal_ipgeo.md
        - PHAL OAuth: PHAL_oauth.md
        - PHAL Wallpaper Manager: phal_wallpaper.md
        - PHAL Mark1 Faceplate: phal_mk1.md
        - PHAL Home Assistant: phal_ha.md
        - PHAL Wifi Setup: ovos_PHAL_plugin_wifi_setup.md
        - WIFI GUI: phal_wifi_gui.md
        - WIFI Balena: phal_balena.md
        - Audio GGWave: ggwave.md
    - GUI Extensions:
        - OVOS Shell: shell.md
        - Plasma Bigscreen: gui_bigscreen.md
        - Mobile: gui_mobile.md
    - Skills:
        - Homescreen: ovos_homescreen.md

theme: readthedocs
