site_name: OVOS User Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Messages:
        - OPM: opm.md
        - Audio: ovos_audio.md
        - Listener: dinkum.md
        - Workshop : skills.md
        - GUI: gui.md
        - Homescreen: ovos_homescreen.md
        - Persona: persona.md

theme: readthedocs
