site_name: OVOS Messages Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Frameworks:
        - Core: ovos_core.md
        - Audio: ovos_audio.md
        - Listener: dinkum.md
        - Workshop : skills.md
        - GUI: gui.md
        - Persona: persona.md
    - Plugins:
        - OPM: opm.md
        - PHAL System: ovos_PHAL_plugin_system.md
        - PHAL IP Geolocation: phal_ipgeo.md
    - Skills:
        - Homescreen: ovos_homescreen.md

theme: readthedocs
