site_name: OVOS User Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Core:
        - Audio: ovos_audio.md
        - Listener: dinkum.md
        - Workshop : skills.md
        - GUI: gui.md
        - Persona: persona.md
    - Plugins:
        - OPM: opm.md
    - Skills:
        - Homescreen: ovos_homescreen.md

theme: readthedocs
